server:
    #端口
    port: 8080
    session:
        #session过期期限
        timeout: 1000 # in seconds
    context-path: /springboot-swagger
    
spring:
    application:
        name: SPRINGBOOT-ACTIVEMQ
            
#日志管理            
logging: 
    level: 
        zqit: debug
            
    
